name: Lint

on:
  push:
    branches:
      - "master"
      - "maintenance/.+"
  pull_request:
    branches:
      - "master"
      - "maintenance/.+"
  schedule:
    # Run a cron job once daily
    - cron: "0 0 * * *"

jobs:
  lint-format:
    name: Lint & format checks
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          installer-url: https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh
          python-version: "3.7"
          activate-environment: test
          channel-priority: true
          environment-file: devtools/conda-envs/test_env.yaml
          auto-activate-base: false
          use-mamba: true

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Environment Information
        shell: bash -l {0}
        run: |
          conda info --all
          conda list

      - name: Install linter / formatter
        shell: bash -l {0}
        run: |
          mamba install pylint black

      - name: Install package
        shell: bash -l {0}
        run: |
          python -m pip install --no-deps .

      - name: Run pylint
        shell: bash -l {0}
        run: |
          pylint --disable=W kinoml/

      - name: Run black check
        shell: bash -l {0}
        if: always()
        run: |
          black --check -l 99 kinoml/ --exclude kinoml/_version.py
